### ISSUE TITLE
Extra dash in the title?

### ISSUE THREAD

**Issue by tomsmith11** [Telqu1n/Blog-site-#6]
How come the title of the repo is "Blog-site-" and not "Blog-Site"
Or, even better, the site could be called "blog_site"

If you end up changing this, be sure to create a pull request and then link the pull request in the issue

**Comment by Telqu1n** [comment]
Thankyou, i have fixed it.

**Comment by tomsmith11** [comment]
You forgot to create the pull request properly you fool!

You shoulda commit to dev, go on GitHub, create pull request, link the pull request in this issue and then merge the pull request


I just looked, and you committed it straight to main aswell from GitHub.com didn't ya 
you FOOL!
Now the changes are not on dev, and then when you make changes on dev and try and push / merge there are going to be conflicts

(Also, for commit messages, do them in past tense. Don't say "adding this", say "added this" or "add this"

@Telqu1n

**Comment by tomsmith11** [comment]
@Telqu1n 

look at the last line of text for the previous comment
